# Generated by Django 5.0.3 on 2024-04-01 18:06

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=myapp.models.default_image, null=True, upload_to='uploads/'),
        ),
    ]
