# Generated by Django 5.0.3 on 2024-04-02 02:26

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=myapp.models.default_image, upload_to='uploads/'),
        ),
    ]
