FROM node:lts-bullseye

# Set working directory
WORKDIR /frontend

# Copy the rest of the application
COPY . .

# Install dependencies
RUN npm install

# Expose the port if needed (e.g., for debugging or development)
EXPOSE 3000

# Start the application
CMD ["npm", "run", "dev"]
