version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - /var/lib/postgresql/data:/Users/aagouzou/goinfre/PgData
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: on-failure
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
  frontend:
    build: .
    hostname: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: on-failure
  backend:
    build: backend
    hostname: backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: on-failure

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: /Users/aagouzou/goinfre/PgData
      o: bind

# /Users/mmaqbour/Desktop/PgData   ====>   MAC
# /home/mmaqbour/Desktop/PgData    ====>   ubuntu