FROM debian:latest

RUN apt update && apt upgrade && apt-get install python3 python3.11-venv -y

WORKDIR /backend

COPY . .

COPY ./script.sh /

RUN chmod +x /script.sh

EXPOSE 8000

CMD [ "/script.sh" ]