# Generated by Django 4.2.11 on 2024-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FinishedTournament',
        ),
    ]
