# Generated by Django 4.2.11 on 2024-05-02 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activematch',
            name='date_ended',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
