# Generated by Django 4.2.11 on 2024-06-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_tournament_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.IntegerField(unique=True),
        ),
    ]
