# Generated by Django 4.2.11 on 2024-05-20 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_friendmatch_participatedfriends'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_player', to='mainApp.activematch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='participatedfriends',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='participatedfriends',
            name='friend_match',
        ),
        migrations.DeleteModel(
            name='FriendMatch',
        ),
        migrations.DeleteModel(
            name='ParticipatedFriends',
        ),
    ]
