# Generated by Django 4.2.11 on 2024-05-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_activematch_date_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activematch',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='activematch',
            name='date_started',
        ),
    ]
