# Generated by Django 4.2.11 on 2024-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_tournamentmembersrank_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmembers',
            name='is_eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
