# Generated by Django 4.2.11 on 2024-07-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_tournamentmembers_is_eliminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmembers',
            name='rank',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='TournamentMembersRank',
        ),
    ]
