# Generated by Django 4.2.11 on 2024-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_tournamentmembers_rank_delete_tournamentmembersrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmembers',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
