# Generated by Django 4.2.11 on 2024-07-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_tournamentmembers_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmembers',
            name='is_inside',
            field=models.BooleanField(default=False),
        ),
    ]
