# Generated by Django 4.2.11 on 2024-07-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_tournamentwarnnotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentwarnnotifications',
            name='user',
        ),
    ]
