# Generated by Django 4.2.11 on 2024-07-13 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_tournamentwarnnotifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentwarnnotifications',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
