# Generated by Django 4.2.11 on 2024-07-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_round_tournamentuserinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmembers',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tournamentmembers',
            name='rank',
        ),
    ]
