# Generated by Django 4.2.11 on 2024-07-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_remove_tournamentmembers_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentuserinfo',
            old_name='positin',
            new_name='position',
        ),
    ]
