# Generated by Django 4.2.11 on 2024-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.TextField(blank=True),
        ),
    ]
