global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - "alert_rules.yml"

remote_write:
- url: "https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push"

  basic_auth:
    username: "1901076"
    password: "glc_eyJvIjoiMTI3MzE5NCIsIm4iOiJzdGFjay0xMDkyMDQyLWhtLXdyaXRlLWVsbWVoZGkta2VuYW5lLXRva2VueCIsImsiOiI2NUM0RTdVMWkzZWY3eEkzM1JQazNud24iLCJtIjp7InIiOiJwcm9kLXVzLWVhc3QtMCJ9fQ=="

scrape_configs:
  - job_name: "backend_application_availability"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/metrics"
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
